### ISSUE TITLE
Does not correctly handle a directive and a filter which have the same name

### ISSUE THREAD

**Issue by thesam** [Tapad/gulp-angular-builder#1]
Given:
- A filter named "x" in module "a":
  `angular.module('a').filter('x',...`
- A directive named "x" in module "b":
  `angular.module("b").directive("x",...`
- An HTML template using both the filter and the directive
  When:
- gulp-angular-builder is run
  Then:
  Only one of them (the filter OR the directive) is included in the output.

Probable reason: HTML tokens are stored in the "definitions" hash, using only the name as a key. It does not consider that the tokens refer to different types nor that they are defined in different modules.

**Comment by jessezhang91** [comment]
Great point! I actually do store the type as well so I will implement something to allow them to have the same names as long as they're different types.

**Comment by thesam** [comment]
Sounds great! Please consider using the module name as well, otherwise all names must be globally unique.

**Comment by jessezhang91** [comment]
I do store that information as well, I believe. However, aren't names required to be globally unique by angularjs? See: http://stackoverflow.com/questions/14909474/namespacing-services-in-angularjs

**Comment by thesam** [comment]
Ah, you are correct, sorry. :)

**Comment by jessezhang91** [comment]
As of 0.3.0 (70cc6886010d12df014505087eeb1884116cb200), filters and directives have their own separate namespace from controllers, services, factories, etc.
