### ISSUE TITLE
Route Resolve Issues

### ISSUE THREAD

**Issue by trisys3** [Tapad/gulp-angular-builder#3]
It seems that `gulp-angular-builder` mostly handles dependencies in route resolves. It seems to resolve modules depended on _by_ resolves, however if a module is _defined_ in a resolve, it does not seem to find it. One other thing: I am using `angular-ui-router`, so I am not sure if this is compounding the issue.

For example, say I have `routes.js`:

```
angular.module('myModule').config(function($stateProvider, rteModDep) {
  $stateProvider
    .state('someState', {
      resolve: {
        myRteMod: ['rteModDep', function(rteModDep) {
          return ...
        }],

        otherRteMod: ['myRteMod', function(myRteMod) {
          return ...
        }]
      }
    });
});
```

This code would throw the error:

```
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: Graph Error
File: routes.js
Component: myRteMod
Reason: Cannot find required component
```

The plugin seems to realize that there is a dependency on a module called "myRteMod" for one of the route resolves. However, it apparently can not see that this module, "myRteMod", is in fact defined in the other route resolve definition. Again, I am not sure if this happens for the core Angular `$routeProvider`, I only know it happens with Angular UI Router's `$stateProvider`.

**Comment by jessezhang91** [comment]
I did not realize the route resolves can depend on each other. I'll add something for the file to remove dependencies for its own resolves.

**Comment by trisys3** [comment]
Thanks, I'll look at it whenever you commit it. Great job with the plugin!

**Comment by jessezhang91** [comment]
This should be fixed in e9d4b5111e46a8bf8fe0a550b17d20a3985b495f.

I tested it against your example and it seems to be requiring the file properly after I removed the rteModDep dependency.

**Comment by trisys3** [comment]
It is, thanks.

**Comment by jessezhang91** [comment]
Awesome! I'm glad to see other people are using this plugin!
